"""add auth fields to employee

Revision ID: b3c96ab5a23c
Revises:
Create Date: 2026-02-25 17:15:43.312269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b3c96ab5a23c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("admin", "manager", "employee", name="role").create(
        op.get_bind(),
        checkfirst=True,
    )
    op.add_column("employee", sa.Column("email", sa.String(), nullable=True))
    op.add_column(
        "employee",
        sa.Column(
            "role",
            sa.Enum("admin", "manager", "employee", name="role"),
            server_default="employee",
            nullable=False,
        ),
    )
    op.add_column("employee", sa.Column("hashed_password", sa.String(), nullable=True))
    op.alter_column(
        "employee",
        "entry_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    op.execute(
        """
        UPDATE employee
        SET email = CONCAT('employee-', id, '@example.local')
        WHERE email IS NULL
        """
    )
    op.execute(
        """
        UPDATE employee
        SET hashed_password = '$pbkdf2-sha256$29000$5Lz3HiOE8B4DIKQUghDCGA$EPr95oJaPF2rhwq6PMMscgVkDbMk.P24rFOs//CA.qo'
        WHERE hashed_password IS NULL
        """
    )
    op.alter_column("employee", "email", nullable=False)
    op.alter_column("employee", "hashed_password", nullable=False)
    op.alter_column("employee", "role", server_default=None)
    op.create_index(op.f("ix_employee_email"), "employee", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_email"), table_name="employee")
    op.alter_column("employee", "role", server_default="employee")
    op.alter_column(
        "employee",
        "entry_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("employee", "hashed_password")
    op.drop_column("employee", "role")
    op.drop_column("employee", "email")
    sa.Enum("admin", "manager", "employee", name="role").drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
